In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import NN_func as nn
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
def neural_network_super_function(ni,k,npl,no,eta,m,n,epochs):
    
    training_set, test_set = nn.create_sets(n)                      #Gimme data!
    
    w, b = nn.network_setup(ni,k,npl,no)                            #Establish neurons and their connections
    
    for r in range(epochs):                                         #For each epoch...
        mini = nn.mini_batch(m,training_set)                        #Prepping mini batch
        for i in range(len(mini)):                                  #For each mini batch...
            for j in range(len(mini[i]['target'])):                 #For each digit in each mini batch...
                x = mini[i]['data'][j]                              #Define x as data input
                y = mini[i]['target'][j]                            #Define y as desired output
            
                z, a = nn.feedforward(w,b,x,k)                      #Find the weighted inputs and activation function returns

                delta = nn.act_error(a,y,z,w,k)                     #Find the error in each neuron
            
                w, b = nn.replace(w,b,eta,m,delta,a)                #Define the new weights and biases!
        print('Epoch {0} Complete'.format(r+1))

    return w, b, test_set

In [3]:
def test_net(w,b,test_set,k):
    
    """
    w, b : weights and balances of trained network
    
    test_set : test set from create_sets function
    
    k : number of hidden layers (for feedforward func)
    
    ******************************************
    
    prints statement
    """
    
    count = 0
    for i in range(len(test_set['target'])):
        x = test_set['data'][i]
        y = test_set['target'][i]
        y_con = np.zeros(10)
        y_con[y] = 1
        z, a = nn.feedforward(w,b,x,k)
        
        out = a[-1]
        max_index = 0
        for j in range(len(out)):
            if out[j] > max_index:
                max_index = out[j]
        for p in range(len(out)):
            if out[p] == max_index:
                out[p] = 1
            else:
                out[p] = 0
                
        correct_indi = 0
        for q in range(len(out)):
            if out[q] == y_con[q]:
                correct_indi += 1
                if correct_indi == 10:
                    count += 1
                
    print('Accuracy: {0}/{1}'.format(count,len(test_set['target'])))
    return a, out, y_con, w, b

In [4]:
ni = 64
k = 1
npl = 10
no = 10
eta = 0.2
m = 10
n = 1000
epochs = 10
w, b, test = neural_network_super_function(ni,k,npl,no,eta,m,n,epochs)
test_net(w,b,test,k)

Epoch 1 Complete
Epoch 2 Complete
Epoch 3 Complete
Epoch 4 Complete
Epoch 5 Complete
Epoch 6 Complete
Epoch 7 Complete
Epoch 8 Complete
Epoch 9 Complete
Epoch 10 Complete
Accuracy: 77/797


([array([  0.,   0.,  11.,  14.,  10.,   1.,   0.,   0.,   0.,   0.,  16.,
          15.,  14.,  13.,   0.,   0.,   0.,   1.,  14.,   8.,   3.,  16.,
           2.,   0.,   0.,   0.,   7.,  16.,  13.,  16.,   2.,   0.,   0.,
           0.,   0.,  12.,  16.,   9.,   0.,   0.,   0.,   0.,   1.,  14.,
          16.,  12.,   0.,   0.,   0.,   0.,  10.,  16.,  15.,  16.,   0.,
           0.,   0.,   0.,   7.,  14.,  15.,  11.,   0.,   0.]),
  array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]),
  array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])],
 array([ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
 [array([[ -2.69201657e-01,   3.95738857e-01,   5.79235782e-01,
            3.23144083e-01,  -9.03926779e-01,   2.17857108e+00,
           -6.65293512e-01,  -6.79007100e-01,   3.40084234e-01,
            7.08026176e-01],
         [  1.04495828e+00,   1.53351950e+00,   1.16858409e+00,
           -9.46995809e-01,   1.